### dev.harrel:json-schema
GET https://search.maven.org/remotecontent?filepath=dev/harrel/json-schema/maven-metadata.xml

### any
GET https://search.maven.org/remotecontent?filepath=org/springframework/spring-context/maven-metadata.xml


