### dev.harrel:json-schema
GET {{url}}/api/v1/packages/dev.harrel:json-schema:1.3.1

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
  client.test("Should be gzipped", function() {
    client.assert(response.headers.valueOf('Content-Encoding') === 'gzip');
  });
%}

### dev.harrel:json-schema with depth=0
GET {{url}}/api/v1/packages/dev.harrel:json-schema:1.3.1?depth=0

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
%}

### com.amazonaws:DynamoDBLocal
// @no-log
GET {{url}}/api/v1/packages/com.amazonaws:DynamoDBLocal:2.0.0

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
  client.test("Should be gzipped", function() {
    client.assert(response.headers.valueOf('Content-Encoding') === 'gzip');
  });
%}

### org.apache.spark:spark-core_2.13
// @no-log
GET {{url}}/api/v1/packages/org.apache.spark:spark-core_2.13:3.4.1

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
  client.test("Should be gzipped", function() {
    client.assert(response.headers.valueOf('Content-Encoding') === 'gzip');
  });
%}
