### analyze and wait
POST {{url}}/api/v1/analyze-and-wait
Content-Type: application/json

{
  "groupId": "dev.harrel",
  "artifactId": "json-schema",
  "version": "1.5.1"
}

> {%
  client.test("Request executed successfully", () => {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### dev.harrel:json-schema
POST {{url}}/api/v1/analyze-and-wait
Content-Type: application/json

{
  "groupId": "dev.harrel",
  "artifactId": "json-schema",
  "version": "1.3.1"
}

> {%
  client.test("Request executed successfully", () => {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### com.amazonaws:DynamoDBLocal
POST {{url}}/api/v1/analyze-and-wait
Content-Type: application/json

{
  "groupId": "com.amazonaws",
  "artifactId": "DynamoDBLocal",
  "version": "2.0.0"
}

> {%
  client.test("Request executed successfully", () => {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### org.apache.spark:spark-core_2.13
POST {{url}}/api/v1/analyze-and-wait
Content-Type: application/json

{
  "groupId": "org.apache.spark",
  "artifactId": "spark-core_2.13",
  "version": "3.4.1"
}

> {%
  client.test("Request executed successfully", () => {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### crawl
POST https://jarhell.harrel.dev/technical/v1/crawl
Content-Type: application/json
Authorization: Bearer

### crawl local
POST http://localhost:8060/technical/v1/crawl
Content-Type: application/json
Authorization: Bearer test