### dev.harrel
GET {{url}}/api/v1/packages/search?query=dev.harrel

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
  client.test("Contains entries", () => {
    client.assert(response.body.some(r => r.g === 'dev.harrel' && r.a === 'json-schema'));
  });
%}

### dev.harrel:json-schema
GET {{url}}/api/v1/packages/search?query=dev.harrel:json-schema

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
  client.test("Contains entries", () => {
    client.assert(response.body.some(r => r.g === 'dev.harrel' && r.a === 'json-schema'));
  });
%}

### json-schema
GET {{url}}/api/v1/packages/search?query=json-schema

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
  client.test("Contains entries", () => {
    client.assert(response.body.some(r => r.g === 'dev.harrel' && r.a === 'json-schema'));
  });
%}

### empty query
GET {{url}}/api/v1/packages/search?query=

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
  client.test("No entries", () => {
    client.assert(response.body.length === 0);
  });
%}

### no query
GET {{url}}/api/v1/packages/search

> {%
  client.test("Response is 400", () => {
    client.assert(response.status === 400);
  });
%}

### sanitization 1
GET {{url}}/api/v1/packages/search?query=json schema

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
%}

### sanitization 2
GET {{url}}/api/v1/packages/search?query=:

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
%}

### sanitization 3
GET {{url}}/api/v1/packages/search?query=1:2:3:4

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
%}

### sanitization 4
GET {{url}}/api/v1/packages/search?query=$$*!

> {%
  client.test("Response is 200", () => {
    client.assert(response.status === 200);
  });
%}
